### PR TITLE
build process fixes and optimizations

### LINKED ISSUE #306: fix wasm optimizer cache

### PR DESCRIPTION
**Pull request by bekauz**
closes #306 , #307 

- fixes cosmwasm optimizer cache path, builds now take much shorter than before
- adjusts contract schema generation path to avoid filename collisions
- sets `QueryResponses` types to reference by absolute path to avoid unused warnings
- (re)generates schemas
- bumps `workspace.package` optimizer version to latest

overall, the build, schema generation, and wasm optimization now generates no warnings and runs faster

### CODE REVIEW

File: optimize.sh [hunk 1]
```diff
@@ -1,13 +1,13 @@
 #!/bin/bash
 if [[ $(uname -m) =~ "arm64" ]]; then \
     docker run --rm -v "$(pwd)":/code \
-        --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
+        --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
```
Comment (stiiifff) [inline optimize.sh:4]: Aha ! 👌

**Review by stiiifff — APPROVED** [review]

File: Cargo.toml [hunk 2]
```diff
@@ -18,7 +19,7 @@ repository = "https://github.com/timewave-computer/covenants"
 optimize = """docker run --rm -v "$(pwd)":/code \
   --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
-  cosmwasm/optimizer:0.15.1
+  cosmwasm/optimizer:0.16.0
```
Comment (keyleu) [inline Cargo.toml:22]: nit: is this script being used anywhere? If not it can maybe just be removed.

File: contracts/astroport-liquid-pooler/schema/raw/execute.json [hunk 3]
```diff
@@ -0,0 +1,52 @@
+{
```
Comment (keyleu) [inline contracts/astroport-liquid-pooler/schema/raw/execute.json:1]: Do we want to commit all the /raw folders?

**Review by keyleu — APPROVED** [review]

File: contracts/astroport-liquid-pooler/schema/raw/execute.json (hunk 3 above)
Comment (bekauz) [reply contracts/astroport-liquid-pooler/schema/raw/execute.json:1]: I think we can get them in to see what the frontend people prefer, later we can adjust?

Comment (bekauz) [reply contracts/astroport-liquid-pooler/schema/raw/execute.json:1]: cc @elenamik
